### PR TITLE
Added expand on hover effect and added original colors to social icons/buttons in index.html

### PR DESCRIPTION
**Pull request by AnirudhKK**
Added expand on hover effect and added original colors to social icons/buttons. Please review my effort and would be great if you could accept. Happy Coding! :)

### CODE REVIEW

**Review by lucaam — APPROVED** [review]

**Comment by lucaam** [comment]
Thanks, I tried to merge your pull request but I missed it and did some changes to my files. Now I use minified files and I had to get your modifications and paste into my minified files to resolve. I really appreciate!

**Comment by AnirudhKK** [comment]
Always welcome :)

**Comment by lucaam** [comment]
> Always welcome :)

Please create another PR based on my actual master, I will merge it in the right way. Don't want to just copy the code and close the request.

**Review by lucaam — CHANGES_REQUESTED** [review]
Can you do the same based on my actual index.html file?

**Review by lucaam — CHANGES_REQUESTED** [review]
Can you do the same based on my actual css file?

**Comment by AnirudhKK** [comment]
Shall I delete my forked repo and create another fork and PR? Well I'm okay if you can copy the code though :p

**Comment by lucaam** [comment]
> Shall I delete my forked repo and create another fork and PR? Well I'm okay if you can copy the code though :p

I think it is the best way. I followed the instructions from Github but I wasn't able to accept in in any way. I prefer to mention you, really like the style!

**Comment by AnirudhKK** [comment]
Thanks! I am re-forking the repo and sending another PR

**Comment by AnirudhKK** [comment]
omg! just saw you're using min css. I'm not familiar with that :P

**Comment by lucaam** [comment]
> omg! just saw you're using min css. I'm not familiar with that :P

You can just unminify and write your code. After that minify again. I use a vscode extension to do that.

**Comment by AnirudhKK** [comment]
Oh cool! On my way!!

**Pull request closed without merging**
